# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import datacluster_pb2 as datacluster__pb2


class DataClusterStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddRedditMessage = channel.unary_unary(
        '/cluster.DataCluster/AddRedditMessage',
        request_serializer=datacluster__pb2.RedditMessage.SerializeToString,
        response_deserializer=datacluster__pb2.Reply.FromString,
        )


class DataClusterServicer(object):

  def AddRedditMessage(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataClusterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddRedditMessage': grpc.unary_unary_rpc_method_handler(
          servicer.AddRedditMessage,
          request_deserializer=datacluster__pb2.RedditMessage.FromString,
          response_serializer=datacluster__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cluster.DataCluster', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
